### ISSUE TITLE
convert出错

### ISSUE THREAD

**Issue by weijjzhang** [hustzxd/yolo2_to_caffe_tool#6]
我在convert caffemodel时到了conv21(conv)这一步出错了，错误如下，这个是哪里出了问题？
Traceback (most recent call last):
  File "convert_weights_to_caffemodel.py", line 84, in <module>
    net.params[pr][0].data[...] = np.reshape(netWeights[count:count + weightSize], dims)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 225, in reshape
    return reshape(newshape, order=order)
ValueError: total size of new array must be unchanged

**Comment by peaceorwell** [comment]
yolo.cfg中有23个conv，而yolo.prototxt中只有22个，我在concat1后面加了一个conv单元，就可以了生成caffemodel了，不过还是会报段错误，暂时还没找到原因。

**Comment by sixsixsix666** [comment]
@ZhouYuSong  请问你生成的caffemodel的performance是否和论文中的接近？

**Comment by peaceorwell** [comment]
我们有大量测试，简单测了几张图片，差别不大，我主要是在caffe2上做yolo9000，还得重新训练，所以不完全一致也行

**Comment by weijjzhang** [comment]
@ZhouYuSong 能把你的yolo.cfg和对应的yolo.prototxt发我参考一下吗？我一直转换不成功，我的邮箱是：zwjsjj@qq.com，不甚感谢~

**Comment by peaceorwell** [comment]
@weijjzhang https://github.com/ZhouYuSong/caffe2/blob/yolo9000/models/yolo2/yolo.prototxt 这是我的prototxt

**Comment by zhanglijun95** [comment]
@PeaceOrwell 你好,请问你的段错误是怎么解决的?

**Comment by huipengzhang** [comment]
Error parsing text-format caffe.NetParameter: 1081:16: Message type "caffe.LayerParameter" has no field named "region_param".请问怎么解决，你们有遇到吗

**Comment by ZhaoMonica** [comment]
@huipengzhang  请问您这个问题解决了吗？
